### PR TITLE
V0.1.3

### PR DESCRIPTION
**Pull request by groupdoll**
- Warning when use semicolon
- Enable no-use-before-define

### CODE REVIEW

**Comment by vannizer** [comment]
I thought we gonna put this one 
```json
no-use-before-define: ["error", { "functions": false }]
```
for writing something like,
```js
doA()

function doA() {...}
```

**Comment by groupdoll** [comment]
@vannizer 
```json
no-use-before-define: ["error", { "functions": false }] 
```
will allow this code which lead to runtime error
```javascript
doB()

class Foo {}

function doB() {
  const foo = new Foo()
}
```

**Comment by vannizer** [comment]
@groupdoll Good point!
But IMO it'll prevent the advantage of writing `functions` after define.

Here is my idea
```js
function longFunctions(data) {
  {
    const sanitizedValue = sanitizer(data)
    const parsedValue = parser(sanitizedValue)
    ....
  }

  function sanitizer(val) { ... }
  function parser(val) {...}
}
```

I'm writing functions after the main tasks for readability, if anyone wanna read my code, what they only needs to do is just read the name of the sub-functions and will know what this function do.

And the reason why I don't write the functions before, cause it'll make reader get confused where to start.

**Comment by groupdoll** [comment]
@vannizer 
I agree with you that to disable no-use-before-define for function have more advantage especially readability. 
So I change the code to enable rule no-use-before-define only for classes and variables.

ps. I think we don't need to fear an error in my example because we alway write tests. : P

**Comment by nuttt** [comment]
@hunt why turn off these?
```
"no-underscore-dangle": "off",
"comma-dangle": "off",
"camelcase": "off",
```

**Comment by vannizer** [comment]
LGTM, let's 🚢

**Pull request merged**
